### ISSUE TITLE
Could not resolve JQuery Error

### ISSUE THREAD

**Issue by danipalli** [htl-perg-2018-19-4ahif/form-validation-example-danipalli#1]
Dear Mr Stropek,

I'm running the HTML Page with "express" npm-package on a local server. Trying to get access to the html-elements with JQuery i get an error called "jQuery requires a window with a document" or "window is not defined". I was searching for more than 2 hours on the web but didn't find a solution how to fix it.

![validation](https://user-images.githubusercontent.com/43641237/48303668-34ebbc00-e50d-11e8-9dd3-cc7ff1c9f79a.PNG)

I would be very grateful, if you could help me with this problem.

Kind Regards
Daniel Pallinger

**Comment by rstropek** [comment]
Hi @danipalli!

*express* is a framework for server-side web development. That means that you can use it to generate HTML or implement Web APIs where all the logic runs on a Node.js-based webserver.

*jquery* on the other hand is a client-side framework. It needs a browser to run.

You are trying to combine both frameworks in a single application. That doesn't work. For this exercise, *express* is not a good option. Your *package.json* already contains scripts using *browser-sync*. That is all you need.

BTW - later in the year, we will use express and you will learn more about this framework. It is commonly used and an interesting piece of technology. However, it is not applicable to the problem of this homework.

Does this help?

Greetings,
Rainer Stropek.

**Comment by danipalli** [comment]
Yes, Thank you 👍
